
import React, { useState, useEffect, useMemo } from 'react';
import { Upload, FileUp, CheckCircle2, AlertCircle, Loader2, ArrowLeft, Settings, Database, Activity, AlertTriangle, LockKeyhole, Wifi, RefreshCcw, Zap, ExternalLink, Trash2, Table, Check, ChevronDown, FileSpreadsheet, Code, Copy, Download, Target } from 'lucide-react';
import { uploadToSupabase, getSupabaseConfig, setSupabaseConfig, testSupabaseConnection } from '../services/supabaseService';

interface AdminPanelProps {
  onBack: () => void;
  onRefreshData: () => void;
}

type AdminTab = 'INPUT' | 'SETTING';
const SETTING_TAB_PASSWORD = "Settingmanbill";

const ALLOWED_COLUMNS = [
  'idpel', 'unit', 'nama', 'alamat', 'blth', 'petugas', 'user', 'latitude', 'longitude', 
  'validasi', 'tegangan', 'arus', 'cosphi', 'indikator', 'sisa_kwh', 'temper', 
  'tutup_meter', 'segel', 'lcd', 'keypad', 'relay', 'tarif_index', 'power_limit', 
  'kwh_kumulatif', 'jml_terminal', 'indi_temper', 'keterangan', 'waktu_jam', 
  'no_meter', 'tarif', 'daya', 'kode_rbm',
  // Invoice Specific Columns - exactly as defined in DB
  'tgl', 'totallembar', 'totalrupiah', 'lunas_mandiri', 'lunas_offline', 'janji_bayar', 'total',
  // WO Kontrak Specific
  'wo_invoice'
];

const NUMERIC_COLUMNS = [
  'latitude', 'longitude', 'tegangan', 'arus', 'cosphi', 
  'sisa_kwh', 'kwh_kumulatif', 'daya', 'power_limit', 'temper',
  'jml_terminal', 'tarif_index',
  'totallembar', 'totalrupiah', 'lunas_mandiri', 'lunas_offline', 'janji_bayar', 'total',
  'wo_invoice'
];

const SQL_SCHEMA_HELP = `-- ==========================================
-- 1. SCRIPT PERBAIKAN SCHEMA (JALANKAN INI)
-- Jika anda mendapat error 'Column not found'
-- ==========================================

-- Pastikan tabel ada
CREATE TABLE IF NOT EXISTS invoice_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tambahkan semua kolom yang dibutuhkan
ALTER TABLE invoice_data ADD COLUMN IF NOT EXISTS tgl TEXT;
ALTER TABLE invoice_data ADD COLUMN IF NOT EXISTS unit TEXT;
ALTER TABLE invoice_data ADD COLUMN IF NOT EXISTS "user" TEXT;
ALTER TABLE invoice_data ADD COLUMN IF NOT EXISTS petugas TEXT;
ALTER TABLE invoice_data ADD COLUMN IF NOT EXISTS totallembar NUMERIC DEFAULT 0;
ALTER TABLE invoice_data ADD COLUMN IF NOT EXISTS totalrupiah NUMERIC DEFAULT 0;
ALTER TABLE invoice_data ADD COLUMN IF NOT EXISTS lunas_mandiri NUMERIC DEFAULT 0;
ALTER TABLE invoice_data ADD COLUMN IF NOT EXISTS lunas_offline NUMERIC DEFAULT 0;
ALTER TABLE invoice_data ADD COLUMN IF NOT EXISTS janji_bayar NUMERIC DEFAULT 0;
ALTER TABLE invoice_data ADD COLUMN IF NOT EXISTS total NUMERIC DEFAULT 0;
ALTER TABLE invoice_data ADD COLUMN IF NOT EXISTS validasi TEXT DEFAULT 'BELUM';

-- ==========================================
-- 2. TABEL WO KONTRAK
-- ==========================================
CREATE TABLE IF NOT EXISTS wo_kontrak (
  unit TEXT PRIMARY KEY,
  wo_invoice NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE wo_kontrak ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Access WO Kontrak" ON wo_kontrak;
CREATE POLICY "Public Access WO Kontrak" ON wo_kontrak FOR ALL USING (true);

-- ==========================================
-- 3. KONFIGURASI KEAMANAN (RLS)
-- ==========================================
ALTER TABLE invoice_data ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Access Invoice" ON invoice_data;
CREATE POLICY "Public Access Invoice" ON invoice_data FOR ALL USING (true);

-- ==========================================
-- 4. SKEMA LENGKAP PRABAYAR (lpb_data)
-- ==========================================
CREATE TABLE IF NOT EXISTS lpb_data (
  idpel TEXT PRIMARY KEY,
  unit TEXT, 
  nama TEXT, 
  alamat TEXT, 
  blth TEXT, 
  petugas TEXT,
  latitude FLOAT8, 
  longitude FLOAT8, 
  validasi TEXT DEFAULT 'BELUM VALIDASI',
  tegangan NUMERIC DEFAULT 0, 
  arus NUMERIC DEFAULT 0, 
  cosphi NUMERIC DEFAULT 0,
  indikator TEXT DEFAULT 'NORMAL', 
  sisa_kwh NUMERIC DEFAULT 0, 
  keterangan TEXT, 
  waktu_jam TEXT, 
  no_meter TEXT, 
  tarif TEXT, 
  daya TEXT, 
  kode_rbm TEXT, 
  tarif_index NUMERIC DEFAULT 0, 
  power_limit NUMERIC DEFAULT 0, 
  kwh_kumulatif NUMERIC DEFAULT 0, 
  temper TEXT, 
  tutup_meter TEXT, 
  segel TEXT, 
  lcd TEXT, 
  keypad TEXT, 
  jml_terminal NUMERIC DEFAULT 0, 
  indi_temper TEXT, 
  relay TEXT, 
  tgl TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE lpb_data ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Access" ON lpb_data;
CREATE POLICY "Public Access" ON lpb_data FOR ALL USING (true);`;

const AdminPanel = ({ onBack, onRefreshData }: AdminPanelProps) => {
  const [activeTab, setActiveTab] = React.useState<AdminTab>('INPUT');
  const [targetTable, setTargetTable] = React.useState<'lpb_data' | 'invoice_data' | 'wo_kontrak'>('lpb_data');
  const [isSettingAuth, setIsSettingAuth] = React.useState(false);
  const [showSqlHelp, setShowSqlHelp] = React.useState(false);
  const [passInput, setPassInput] = React.useState('');
  const [file, setFile] = React.useState<File | null>(null);
  const [loading, setLoading] = React.useState(false);
  const [previewData, setPreviewData] = React.useState<any[]>([]);
  const [mappedColumns, setMappedColumns] = React.useState<string[]>([]);
  const [uploadProgress, setUploadProgress] = React.useState({ current: 0, total: 0 });
  const [status, setStatus] = React.useState<{ type: 'success' | 'error' | null, message: string }>({ type: null, message: '' });
  
  const [supabaseUrl, setSupabaseUrl] = React.useState('');
  const [supabaseKey, setSupabaseKey] = React.useState('');

  React.useEffect(() => {
    const config = getSupabaseConfig();
    setSupabaseUrl(config.url);
    setSupabaseKey(config.key);
  }, []);

  const copySql = () => {
    navigator.clipboard.writeText(SQL_SCHEMA_HELP);
    alert('SQL Skema disalin! Tempelkan di SQL Editor Supabase Anda dan klik RUN.');
  };

  const downloadTemplate = async () => {
    const XLSX = await import('xlsx');
    let headers: string[] = [];
    let filename = "";

    if (targetTable === 'lpb_data') {
      headers = [
        'IDPEL', 'UNIT', 'NAMA', 'ALAMAT', 'BLTH', 'PETUGAS', 'LATITUDE', 'LONGITUDE', 
        'VALIDASI', 'TEGANGAN', 'ARUS', 'COSPHI', 'INDIKATOR', 'SISA_KWH', 'TEMPER', 
        'TUTUP_METER', 'SEGEL', 'LCD', 'KEYPAD', 'RELAY', 'TARIF_INDEX', 'POWER_LIMIT', 
        'KWH_KUMULATIF', 'JML_TERMINAL', 'INDI_TEMPER', 'KETERANGAN', 'WAKTU_JAM', 
        'NO_METER', 'TARIF', 'DAYA', 'KODE_RBM'
      ];
      filename = "template_prabayar_lpb.xlsx";
    } else if (targetTable === 'invoice_data') {
      headers = [
        'TGL', 'UNIT', 'USER', 'PETUGAS', 'TotalLembar', 'TotalRupiah', 'Lunas Mandiri', 'Lunas Offline', 'Janji Bayar', 'TOTAL'
      ];
      filename = "template_invoice_tagihan.xlsx";
    } else {
      headers = ['UNIT', 'WO_INVOICE'];
      filename = "template_wo_kontrak.xlsx";
    }

    // Create Excel workbook
    const worksheet = XLSX.utils.aoa_to_sheet([headers]);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, "Template");
    
    // Generate buffer and download
    XLSX.writeFile(workbook, filename);
  };

  const fixScientific = (str: string) => {
    if (!str) return '';
    let s = String(str).toUpperCase().trim();
    if (!s.includes('E+')) return s;
    try {
      const num = Number(s.replace(',', '.'));
      if (!isNaN(num)) return BigInt(Math.round(num)).toString();
    } catch (e) {}
    return s;
  };

  const cleanNumeric = (val: any): number | null => {
    if (val === undefined || val === null || val === '') return null;
    let str = String(val).trim();
    if (str === '') return null;
    str = str.replace(/[^0-9,.-]/g, '');
    const lastComma = str.lastIndexOf(',');
    const lastDot = str.lastIndexOf('.');
    if (lastComma > lastDot) str = str.replace(/\./g, '').replace(',', '.');
    else if (lastDot > lastComma) str = str.replace(/,/g, '');
    else str = str.replace(',', '.');
    const parsed = parseFloat(str);
    return isNaN(parsed) ? null : parsed;
  };

  const parseFile = async (file: File, isPreview: boolean = false): Promise<any[]> => {
    const XLSX = await import('xlsx');
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = (e) => {
        try {
          const data = e.target?.result;
          const workbook = XLSX.read(data, { type: 'binary' });
          const firstSheetName = workbook.SheetNames[0];
          const worksheet = workbook.Sheets[firstSheetName];
          const rows = XLSX.utils.sheet_to_json(worksheet, { header: 1 }) as any[][];
          
          if (rows.length < 1) {
            resolve([]);
            return;
          }

          const headers = (rows[0] as any[]).map(h => String(h || '').trim().toUpperCase());
          const result = [];
          const limit = isPreview ? Math.min(8, rows.length) : rows.length;
          const detectedMappedKeys: string[] = [];

          for (let i = 1; i < limit; i++) {
            const vals = rows[i];
            if (!vals || vals.length === 0) continue;
            const obj: any = {};
            
            headers.forEach((h, idx) => {
              let key = '';
              const rawHeader = h.trim();

              // Specific Mapping Rules
              if (rawHeader === "IDPEL" || rawHeader.includes("ID PEL")) key = "idpel";
              else if (rawHeader.includes("NAMA")) key = "nama";
              else if (rawHeader === "UNIT") key = "unit";
              else if (rawHeader === "USER") key = "user";
              else if (rawHeader === "PETUGAS" || rawHeader === "PEGAWAI") key = "petugas";
              else if (rawHeader.includes("BLTH")) key = "blth";
              else if (rawHeader === "LATITUDE" || rawHeader === "Y" || rawHeader.includes("KOORDINAT Y") || rawHeader.includes("LAT")) key = "latitude";
              else if (rawHeader === "LONGITUDE" || rawHeader === "X" || rawHeader.includes("KOORDINAT X") || rawHeader.includes("LONG")) key = "longitude";
              else if (rawHeader === "TGL" || rawHeader === "TANGGAL" || rawHeader === "TGL_BAYAR") key = "tgl";
              else if (rawHeader === "TOTALLEMBAR" || rawHeader === "TOTAL_LEMBAR" || rawHeader === "TOTAL LEMBAR") key = "totallembar";
              else if (rawHeader === "TOTALRUPIAH" || rawHeader === "TOTAL_RUPIAH" || rawHeader === "TOTAL RUPIAH") key = "totalrupiah";
              else if (rawHeader.includes("LUNAS MANDIRI") || rawHeader === "LM" || rawHeader === "MANDIRI") key = "lunas_mandiri";
              else if (rawHeader.includes("LUNAS OFFLINE") || rawHeader === "OFFLINE") key = "lunas_offline";
              else if (rawHeader.includes("JANJI BAYAR") || rawHeader === "JANJI") key = "janji_bayar";
              else if (rawHeader === "TOTAL") key = "total";
              else if (rawHeader === "WO_INVOICE" || rawHeader.includes("WO INVOICE")) key = "wo_invoice";
              else {
                key = rawHeader.toLowerCase().replace(/\s+/g, '_');
              }

              if (targetTable === 'invoice_data' && key === 'idpel') return;

              if (ALLOWED_COLUMNS.includes(key)) {
                if (i === 1 && !detectedMappedKeys.includes(key)) detectedMappedKeys.push(key);
                let val = vals[idx] !== undefined ? String(vals[idx]) : '';
                if (key === 'idpel') val = fixScientific(val);
                if (NUMERIC_COLUMNS.includes(key)) obj[key] = cleanNumeric(val);
                else obj[key] = val;
              }
            });

            if (targetTable === 'lpb_data') {
              if (obj.idpel) result.push(obj);
            } else if (targetTable === 'invoice_data') {
              if (obj.petugas || obj.user) result.push(obj);
            } else {
              if (obj.unit) result.push(obj);
            }
          }

          if (isPreview) setMappedColumns(detectedMappedKeys);
          resolve(result);
        } catch (error) {
          reject(error);
        }
      };
      reader.onerror = (error) => reject(error);
      reader.readAsBinaryString(file);
    });
  };

  React.useEffect(() => {
    if (file) {
      parseFile(file, true).then(data => {
        setPreviewData(data);
      }).catch(err => {
        console.error("Preview error:", err);
        setPreviewData([]);
      });
    } else {
      setPreviewData([]);
      setMappedColumns([]);
    }
  }, [file, targetTable]);

  const handleUpload = async () => {
    if (!file) return;
    setLoading(true);
    setStatus({ type: null, message: '' });
    
    try {
      const rawData = await parseFile(file, false);
      
      if (rawData.length === 0) {
        throw new Error('Data tidak valid atau kolom kunci tidak ditemukan.');
      }

      let allData = rawData;
      if (targetTable === 'lpb_data') {
        const uniqueDataMap = new Map();
        rawData.forEach(item => uniqueDataMap.set(item.idpel, item));
        allData = Array.from(uniqueDataMap.values());
      } else if (targetTable === 'wo_kontrak') {
        const uniqueDataMap = new Map();
        rawData.forEach(item => uniqueDataMap.set(item.unit, item));
        allData = Array.from(uniqueDataMap.values());
      }
      
      const chunkSize = 500;
      const total = Math.ceil(allData.length / chunkSize);
      setUploadProgress({ current: 0, total });

      for (let i = 0; i < allData.length; i += chunkSize) {
        const chunk = allData.slice(i, i + chunkSize);
        const res = await uploadToSupabase(chunk, targetTable);
        if (!res.success) {
          if (res.message.includes('PGRST204') || (res.message.includes('column') && res.message.includes('not found'))) {
            throw new Error(`SCHEMA MISMATCH: Database Supabase Anda kekurangan kolom. Klik tombol 'SQL SCHEMA HELP' dan jalankan script perbaikan.`);
          }
          throw new Error(res.message);
        }
        setUploadProgress(prev => ({ ...prev, current: prev.current + 1 }));
      }

      setStatus({ 
        type: 'success', 
        message: `Sinkronisasi Berhasil: ${allData.length} data dikirim ke tabel ${targetTable.toUpperCase()}.` 
      });
      setFile(null);
      onRefreshData();
    } catch (err: any) {
      setStatus({ type: 'error', message: err.message });
    } finally {
      setLoading(false);
    }
  };

  const isCompatible = React.useMemo(() => {
    if (targetTable === 'lpb_data') return mappedColumns.includes('idpel');
    if (targetTable === 'wo_kontrak') return mappedColumns.includes('unit') && mappedColumns.includes('wo_invoice');
    return mappedColumns.includes('petugas') || mappedColumns.includes('user');
  }, [mappedColumns, targetTable]);

  return (
    <div className="bg-white border-2 border-slate-300 rounded-[40px] flex flex-col h-full shadow-2xl overflow-hidden fade-in">
      <div className="bg-slate-950 p-8 flex items-center justify-between shrink-0">
        <div className="flex items-center gap-6">
          <button onClick={onBack} className="p-3 bg-white/5 hover:bg-white/10 rounded-2xl text-slate-400 hover:text-white transition-all">
            <ArrowLeft size={24} />
          </button>
          <div>
            <h2 className="text-base font-black text-white uppercase tracking-[0.2em] italic leading-none flex items-center gap-3">
              <Zap size={20} className="text-emerald-500 fill-emerald-500" /> PUSAT KONTROL DATA
            </h2>
            <div className="flex items-center gap-4 mt-2">
               <p className="text-[10px] font-bold text-slate-500 uppercase tracking-widest italic leading-none">Secure Supabase Tunnel Active</p>
               <button onClick={() => setShowSqlHelp(!showSqlHelp)} className="text-[10px] font-black text-indigo-400 hover:text-white uppercase tracking-widest flex items-center gap-2">
                 <Code size={12}/> SQL SCHEMA HELP (FIX DB ERRORS)
               </button>
            </div>
          </div>
        </div>
        <div className="flex bg-white/5 p-1.5 rounded-2xl border border-white/5">
          <button onClick={() => setActiveTab('INPUT')} className={`px-6 py-2.5 rounded-xl text-[10px] font-black uppercase transition-all ${activeTab === 'INPUT' ? 'bg-indigo-600 text-white shadow-xl' : 'text-slate-400 hover:text-slate-200'}`}>SINKRONISASI</button>
          <button onClick={() => setActiveTab('SETTING')} className={`px-6 py-2.5 rounded-xl text-[10px] font-black uppercase transition-all ${activeTab === 'SETTING' ? 'bg-indigo-600 text-white shadow-xl' : 'text-slate-400 hover:text-slate-200'}`}>PENGATURAN</button>
        </div>
      </div>

      <div className="flex-1 p-8 overflow-auto bg-slate-50/50 relative">
        {showSqlHelp && (
          <div className="absolute top-0 left-0 right-0 z-50 p-8 fade-in">
            <div className="bg-slate-900 border border-white/10 rounded-3xl p-6 shadow-2xl space-y-4">
              <div className="flex justify-between items-center">
                <div className="flex flex-col">
                  <h4 className="text-xs font-black text-indigo-400 uppercase">Perbaikan Struktur Database</h4>
                  <p className="text-[9px] text-slate-500 font-bold uppercase tracking-widest mt-1">Salin dan Jalankan script di bawah ini pada SQL Editor Supabase</p>
                </div>
                <div className="flex gap-2">
                   <button onClick={copySql} className="p-2 bg-emerald-600 hover:bg-emerald-700 rounded-xl text-white transition-all flex items-center gap-2 text-[9px] font-black uppercase tracking-widest px-4"><Copy size={16}/> SALIN SKEMA FIX</button>
                   <button onClick={() => setShowSqlHelp(false)} className="p-2 bg-rose-500/20 hover:bg-rose-500 text-white rounded-xl transition-all">TUTUP</button>
                </div>
              </div>
              <pre className="text-[9px] font-mono text-slate-400 overflow-x-auto whitespace-pre-wrap leading-relaxed max-h-[400px] border border-white/5 p-4 rounded-xl bg-black/30">
                {SQL_SCHEMA_HELP}
              </pre>
            </div>
          </div>
        )}

        {activeTab === 'SETTING' ? (
          !isSettingAuth ? (
            <div className="flex justify-center py-20">
              <form onSubmit={(e) => { e.preventDefault(); passInput === SETTING_TAB_PASSWORD ? setIsSettingAuth(true) : alert('Password Otorisasi Salah'); }} className="bg-white p-10 rounded-[40px] border-2 border-slate-200 shadow-2xl w-full max-w-md space-y-6">
                <div className="text-center space-y-2">
                   <div className="p-4 bg-slate-900 text-indigo-400 rounded-3xl w-fit mx-auto mb-4"><LockKeyhole size={32}/></div>
                   <h3 className="text-xl font-black uppercase tracking-tight">Otorisasi Akses</h3>
                </div>
                <input type="password" value={passInput} onChange={(e)=>setPassInput(e.target.value)} className="w-full bg-slate-50 border-2 border-slate-200 rounded-2xl px-6 py-4 text-center font-black text-lg focus:border-indigo-600 outline-none transition-all" placeholder="••••••••" />
                <button type="submit" className="w-full py-5 bg-slate-950 text-white rounded-2xl font-black uppercase tracking-widest text-xs hover:bg-indigo-700 transition-all">Verifikasi Identitas</button>
              </form>
            </div>
          ) : (
            <div className="max-w-3xl mx-auto space-y-6">
               <div className="bg-white p-8 border border-slate-200 rounded-[32px] shadow-sm space-y-6">
                  <div className="flex items-center gap-3 border-b border-slate-100 pb-4">
                    <Settings size={20} className="text-indigo-600"/>
                    <h3 className="text-sm font-black uppercase text-slate-900">Konfigurasi Endpoint API</h3>
                  </div>
                  <div className="space-y-4">
                    <div>
                       <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1 mb-1 block">Supabase URL</label>
                       <input type="text" value={supabaseUrl} onChange={(e)=>setSupabaseUrl(e.target.value)} placeholder="https://xxxx.supabase.co" className="w-full bg-slate-50 border-2 border-slate-200 rounded-xl px-4 py-3 text-xs font-mono font-bold" />
                    </div>
                    <div>
                       <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1 mb-1 block">Service Role API Key</label>
                       <input type="password" value={supabaseKey} onChange={(e)=>setSupabaseKey(e.target.value)} placeholder="Supabase Key" className="w-full bg-slate-50 border-2 border-slate-200 rounded-xl px-4 py-3 text-xs font-mono font-bold" />
                    </div>
                  </div>
                  <button onClick={() => { setSupabaseConfig({ url: supabaseUrl, key: supabaseKey }); alert('Konfigurasi Disimpan.'); }} className="w-full py-4 bg-indigo-600 text-white rounded-2xl text-xs font-black uppercase hover:bg-indigo-700 transition-all">Update Parameter Sistem</button>
               </div>
            </div>
          )
        ) : (
          <div className="max-w-5xl mx-auto space-y-8">
            <div className="bg-white p-8 border border-slate-200 rounded-[32px] shadow-sm flex items-center justify-between">
              <div>
                <h3 className="text-sm font-black uppercase text-slate-900">Database Target Sinkronisasi</h3>
                <p className="text-[10px] font-bold text-slate-400 uppercase mt-1 tracking-widest">Pilih tabel database untuk menerima data Excel/CSV Anda</p>
              </div>
              <div className="flex items-center gap-4">
                <div className="flex bg-slate-100 p-1.5 rounded-2xl">
                  <button onClick={() => setTargetTable('lpb_data')} className={`px-6 py-3 rounded-xl text-[10px] font-black uppercase transition-all flex items-center gap-2 ${targetTable === 'lpb_data' ? 'bg-indigo-600 text-white shadow-lg' : 'text-slate-500 hover:text-slate-900'}`}><Database size={14}/> Prabayar</button>
                  <button onClick={() => setTargetTable('invoice_data')} className={`px-6 py-3 rounded-xl text-[10px] font-black uppercase transition-all flex items-center gap-2 ${targetTable === 'invoice_data' ? 'bg-indigo-600 text-white shadow-lg' : 'text-slate-500 hover:text-slate-900'}`}><FileSpreadsheet size={14}/> Invoice</button>
                  <button onClick={() => setTargetTable('wo_kontrak')} className={`px-6 py-3 rounded-xl text-[10px] font-black uppercase transition-all flex items-center gap-2 ${targetTable === 'wo_kontrak' ? 'bg-indigo-600 text-white shadow-lg' : 'text-slate-500 hover:text-slate-900'}`}><Target size={14}/> WO Kontrak</button>
                </div>
                <button 
                  onClick={downloadTemplate}
                  className="flex items-center gap-2 px-6 py-3 bg-white border-2 border-slate-200 hover:border-indigo-500 hover:text-indigo-600 rounded-2xl text-[10px] font-black uppercase transition-all shadow-sm"
                >
                  <Download size={14} /> Download Template
                </button>
              </div>
            </div>

            <div className={`bg-white border-4 border-dashed rounded-[40px] p-12 flex flex-col items-center gap-6 transition-all ${file ? 'border-emerald-500 bg-emerald-50/10' : 'border-slate-200 hover:border-indigo-400'}`}>
              <div className={`p-8 rounded-[32px] ${file ? 'bg-emerald-600 text-white shadow-2xl' : 'bg-slate-100 text-slate-300'}`}><FileUp size={48} /></div>
              <div className="text-center space-y-2">
                <p className="text-lg font-black uppercase text-slate-900 tracking-tight">{file ? file.name : 'Seret File Excel/CSV ke Sini'}</p>
                <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Mendukung Format .xlsx, .xls, dan .csv</p>
              </div>
              <input type="file" accept=".csv,.xlsx,.xls" onChange={(e)=>setFile(e.target.files?.[0] || null)} className="hidden" id="admin-csv-upload-main" />
              <label htmlFor="admin-csv-upload-main" className="px-10 py-4 bg-slate-950 text-white text-[11px] font-black uppercase rounded-2xl cursor-pointer hover:bg-indigo-600 transition-all shadow-2xl">
                {file ? 'GANTI FILE' : 'PILIH DARI PERANGKAT'}
              </label>
            </div>

            {file && (
              <div className="bg-white border border-slate-200 rounded-[32px] overflow-hidden shadow-sm fade-in">
                <div className="bg-slate-900 px-8 py-5 flex items-center justify-between">
                  <h4 className="text-[11px] font-black uppercase text-white tracking-[0.2em] flex items-center gap-3"><Table size={16} className="text-indigo-400"/> Mapping Preview</h4>
                  <div className={`px-4 py-2 rounded-xl text-[10px] font-black uppercase flex items-center gap-2 ${isCompatible ? 'bg-emerald-500 text-white' : 'bg-rose-500 text-white'}`}>
                    {isCompatible ? <Check size={14}/> : <AlertCircle size={14}/>}
                    {isCompatible ? `Sesuai Target ${targetTable.toUpperCase()}` : 'Format Tidak Sesuai'}
                  </div>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full text-left border-collapse">
                    <thead className="bg-slate-50 text-[9px] font-black uppercase text-slate-400 border-b border-slate-100">
                      <tr>
                        {targetTable === 'lpb_data' ? (
                          ['idpel', 'unit', 'nama', 'petugas', 'latitude', 'longitude'].map(col => <th key={col} className="px-6 py-4 border-r border-slate-100">{col}</th>)
                        ) : targetTable === 'invoice_data' ? (
                          ['tgl', 'unit', 'user', 'petugas', 'totallembar', 'totalrupiah', 'lunas_mandiri', 'lunas_offline', 'janji_bayar', 'total'].map(col => <th key={col} className="px-6 py-4 border-r border-slate-100">{col}</th>)
                        ) : (
                          ['unit', 'wo_invoice'].map(col => <th key={col} className="px-6 py-4 border-r border-slate-100">{col}</th>)
                        )}
                      </tr>
                    </thead>
                    <tbody className="text-[11px] font-bold text-slate-600">
                      {previewData.map((row, idx) => (
                        <tr key={idx} className="border-b border-slate-50 hover:bg-slate-50/50">
                          {targetTable === 'lpb_data' ? (
                            <>
                              <td className="px-6 py-3 font-mono text-indigo-600 font-black">{row.idpel}</td>
                              <td className="px-6 py-3 uppercase">{row.unit}</td>
                              <td className="px-6 py-3 uppercase truncate max-w-[150px]">{row.nama}</td>
                              <td className="px-6 py-3 uppercase italic text-slate-400">{row.petugas}</td>
                              <td className="px-6 py-3 text-slate-400 font-mono">{row.latitude}</td>
                              <td className="px-6 py-3 text-slate-400 font-mono">{row.longitude}</td>
                            </>
                          ) : targetTable === 'invoice_data' ? (
                            <>
                              <td className="px-6 py-3 font-mono">{row.tgl}</td>
                              <td className="px-6 py-3 uppercase">{row.unit}</td>
                              <td className="px-6 py-3 font-black text-indigo-600">{row.user}</td>
                              <td className="px-6 py-3 uppercase italic font-black text-slate-900">{row.petugas}</td>
                              <td className="px-6 py-3 text-center">{row.totallembar}</td>
                              <td className="px-6 py-3 font-mono text-xs">{row.totalrupiah?.toLocaleString()}</td>
                              <td className="px-6 py-3 text-emerald-600 font-black text-center">{row.lunas_mandiri}</td>
                              <td className="px-6 py-3 text-blue-600 font-black text-center">{row.lunas_offline}</td>
                              <td className="px-6 py-3 text-amber-600 font-black text-center">{row.janji_bayar}</td>
                              <td className="px-6 py-3 text-slate-950 font-black text-center bg-slate-100/50">{row.total}</td>
                            </>
                          ) : (
                            <>
                              <td className="px-6 py-3 uppercase font-black">{row.unit}</td>
                              <td className="px-6 py-3 font-mono text-indigo-600">{row.wo_invoice}</td>
                            </>
                          )}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {loading && (
              <div className="bg-white border-2 border-emerald-100 rounded-[28px] p-8 space-y-4 shadow-xl">
                 <div className="flex justify-between text-xs font-black uppercase text-emerald-700">
                    <span className="flex items-center gap-3 animate-pulse"><Loader2 className="animate-spin" size={16}/> MENGUNGGAH BATCH DATA...</span>
                    <span>{uploadProgress.current} / {uploadProgress.total} BATCH</span>
                 </div>
                 <div className="w-full bg-slate-100 h-3 rounded-full overflow-hidden">
                    <div className="bg-emerald-500 h-full transition-all duration-500 ease-out" style={{width: `${(uploadProgress.current/uploadProgress.total)*100}%`}}></div>
                 </div>
              </div>
            )}

            {status.type && (
              <div className={`p-6 rounded-[28px] border-2 flex items-center gap-5 shadow-lg animate-in slide-in-from-bottom-4 ${status.type === 'success' ? 'bg-emerald-50 border-emerald-100 text-emerald-700' : 'bg-rose-50 border-rose-100 text-rose-700'}`}>
                <div className={`p-3 rounded-2xl ${status.type === 'success' ? 'bg-emerald-500 text-white' : 'bg-rose-500 text-white'}`}>
                   {status.type === 'success' ? <CheckCircle2 size={24} /> : <AlertTriangle size={24} />}
                </div>
                <div className="flex flex-col">
                  <p className="text-xs font-black uppercase italic tracking-tight">{status.message}</p>
                  {status.type === 'error' && (status.message.includes('SCHEMA MISMATCH') || status.message.includes('column')) && (
                    <p className="text-[10px] font-bold mt-1 text-rose-400">Silahkan salin script SQL melalui tombol 'SQL SCHEMA HELP' dan jalankan di SQL Editor Supabase Anda.</p>
                  )}
                </div>
              </div>
            )}

            <button 
              disabled={!file || !isCompatible || loading} 
              onClick={handleUpload} 
              className={`w-full py-6 rounded-3xl flex items-center justify-center gap-5 text-sm font-black uppercase transition-all shadow-2xl ${!file || !isCompatible || loading ? 'bg-slate-200 text-slate-400' : 'bg-slate-950 text-white hover:bg-emerald-700 hover:shadow-emerald-500/20 active:scale-95'}`}
            >
              {loading ? <Loader2 className="animate-spin" size={20} /> : <Database size={20} />}
              {loading ? 'MEMPROSES DATA...' : `SINKRONISASI KE ${targetTable.toUpperCase()}`}
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default AdminPanel;
